### ISSUE TITLE
npm install报错

### ISSUE THREAD

**Issue by JeremyZheng** [ckinmind/apple-basket-redux#16]
$ npm install
npm WARN deprecated isparta-instrumenter-loader@1.0.1: isparta-instrumenter-loader is deprecated. Please use isparta-loader instead
npm WARN prefer global node-gyp@3.6.0 should be installed with -g

> phantomjs-prebuilt@2.1.14 install D:\workspace\FrontEnd\apple-basket-redux\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\ZHENGS~1\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 54.231.97.208:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

Please report this full log at https://github.com/Medium/phantomjs

....
...
...

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\work\\nodejs\\node.exe" "D:\\work\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\workspace\FrontEnd\apple-basket-redux\npm-debug.log

**Comment by suntaogit** [comment]
我也是一样的情况！

**Comment by ckinmind** [comment]
@JeremyZheng @suntaogit   很抱歉，看问题好像是下载phantomjs-prebuilt包遇到问题，我之前都是使用cnpm下载的没遇到问题，使用npm install就遇到问题，你试试使用cnpm install方式，使用淘宝源可以下载到这个包

参考资料：[PhantomJS not found on PATH](https://github.com/xhlwill/blog/issues/11)
